---
abstract: 'Write Markdown syntax tables from data'
author:
  - 'Jakob Voß <jakob.voss@gbv.de>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.038
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-MarkdownTable
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  IO::Handle::Util: 0.01
  Moo: 1.0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/nichtich/Text-MarkdownTable/issues
  homepage: https://github.com/nichtich/Text-MarkdownTable
  repository: https://github.com/nichtich/Text-MarkdownTable.git
version: 0.2.4
x_contributors:
  - 'Jakob Voss <jakob@nichtich.de>'
  - 'Jakob Voss <voss@gbv.de>'
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
